### ISSUE TITLE
Add a Try Again into the try catch structure.

### ISSUE THREAD

**Issue by bjstigall** [dotnet/vblang#179]
Add a Try Again into the try catch structure. 
Try 
<some code> 
Catch (ex as exception) 
if exception = bad file name then get new filename 
try again 
finally 
close the file 
end try

**Comment by AnthonyDGreen** [comment]
You can easily accomplish this today by putting a label in the Try and using a Goto statement in the Catch.

**Comment by bjstigall** [comment]
You could, but goto is not good practice. You could do the same thing with goto and if statements for a while loop but we don’t.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by reduckted** [comment]
Or use a loop. Equivalent code that;s actually valid VB syntax:
```vb
Private Sub DoSomething()
    Try
        Do
            Try
                GetSomeFile()
                Exit Do

            Catch ex As Exception When IsBadFileName(ex)
                ' Loop again.
            End Try
        Loop

    Catch ex As Exception
        ' Handle the error.

    Finally
        ' Close the file.
    End Try
End Sub


Private Function IsBadFileName(ex As Exception) As Boolean
    ' ...
End Function
```

**Comment by AnthonyDGreen** [comment]
Well, I think what you want is an "atomic" file open-check to avoid a race condition. So what you really want is something like this:

``` VB.NET
Imports System.IO

Module Module1
    Sub Main()

        Dim tryOpenFile = Function(path As String, ByRef stream As FileStream, ByRef errorMessage As String) As Boolean
                              Try
                                  stream = File.Open(path, FileMode.Open)
                                  errorMessage = Nothing
                                  Return True
                              Catch ex As IOException
                                  stream = Nothing
                                  errorMessage = ex.Message
                                  Return False
                              End Try
                          End Function

        Dim filename As String = "c:\log.txt",
            log As FileStream = Nothing,
            failureMessage As String = Nothing,
            retryCount = 0

        Do Until tryOpenFile(filename, log, failureMessage)
            Console.WriteLine(failureMessage)

            If retryCount > 10 Then
                Console.WriteLine($"Giving up after {retryCount - 1} attemps.")
                End ' Just die already.
            End If

            ' Fix it!
            retryCount += 1

            Console.WriteLine("Retrying...")
            Console.WriteLine()
        Loop

        Using writer = New StreamWriter(log)
            For i = 1 To 10
                writer.WriteLine($"Line #{i}.")
            Next
        End Using

    End Sub
End Module
```

Or failing that, the `Goto` approach. If you look [here](http://source.roslyn.io/#Microsoft.CodeAnalysis.VisualBasic/Scanner/Scanner.vb,2226) you'll see code in the VB compiler that uses `Goto` because it's the most straight-forward way to express the flow of execution. The Roslyn code-base has plenty of uses of `Goto` where appropriate.

Despite popular superstition `Goto` isn't "bad practice" because that particular sequence of four characters is somehow cursed, but rather because there are more structured statements available in modern languages which better represent your intent to readers, specifically loops, blocks, and structured exception handling (`Try`/`Catch`/`Finally`). A reader has to reverse engineer a sequence of `If`s and `Goto`s to interpret your intent to loop a certain number of times or based on a certain condition and that's why `For` and `While` loops are more clear there. Statements like `Continue`, `Exit`, and `Return` are _barely_ better than `Goto`. You don't have any more expressive statements available for jumping from the `Catch` block back to the beginning of the `Try` and there's no reverse engineering a reader has to do to comprehend your intent of the flow of the code, so `Goto` is a perfectly acceptable way to express it.

This is why languages like VB and C# include `Goto` despite being designed decades after structured programming became popular and we shouldn't add new jump statements _purely_ for avoiding the stigma of an otherwise legitimate programming primitive.

Also, you should use exception handling for actually exceptional circumstances, [not for control flow](https://docs.microsoft.com/en-us/visualstudio/profiling/da0007-avoid-using-exceptions-for-control-flow). This request is specifically to make the `Try` block better suited for something that is not good practice and two wrongs don't make a right :)

**Comment by bjstigall** [comment]
I only used a file open as an example. I wasn’t looking for something specifically for opening a file.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by AnthonyDGreen** [comment]
Right, but that was just an example of the kind of transformation you would apply. It's not file-opening-specific. If you have a real world example of being in this situation it might clarify.

**Comment by AdamSpeight2008** [comment]
@AnthonyDGreen  @bjstigall 
Another approach is conditional exception filters.
```vbnet
Dim TryCount = 3
_Retry:
Try
    ' ...
  Catch ioex As IOException When TryCount > 0
    TryCount-=1
    GoTo _Retry
  Catch ioex As IOException 
    ' Ran out of tries.
  Catch ex As Exception
    '
  Finally

End Try
```
