### ISSUE TITLE
Open non code files with the approprate application

### ISSUE THREAD

**Issue by tverweij** [dotnet/vblang#261]
When you double click on a PDF file, it is opened as a text file in the source editor.
It would be nice if it opened with the default PDF reader instead. Same for all other non code files.

**Comment by sharwell** [comment]
⚠️ I've accidentally run destructive scripts in either Eclipse or IntelliJ because the script file opened in this manner instead of opening in the text editor. We need to be certain not to introduce a behavior change allowing this to occur.

**Comment by tverweij** [comment]
As a solution for this problem: a solution file property that states if the file must be opened in the source editor or with an external application - only available if the build action is "content".

**Comment by ocdtrekkie** [comment]
@tverweij I think I mark my batch files as content in my code, because I don't expect the editor to monkey with them. But I'd prefer them opened in the editor rather than executed if I click them.

It would be arguably decent to open *specific* file formats with the Windows default, but this isn't something that should be blanket applied to "all other non-code files". Anything that can be edited Notepad, more or less, should be opened in the code editor, including arbitrary formats users have for their software.

So my vote (I don't really have a vote, let's be honest) is specific file formats that are common that VS can't parse, yes. "All other non code files", most definitely no.

**Comment by ocdtrekkie** [comment]
Also, sidebar question for the maintainers: Is this is best place for Visual Studio usability issues, like this one? I would've assumed no, because it's "vblang", but if not, it'd be great to know if there's a better place.

**Comment by sharwell** [comment]
@ocdtrekkie It's probably not the best place. The best place is typically specific to a product area, but you should be able to provide feedback and get in contact with relevant groups by using the Report a Problem tool or asking in the [Microsoft/VisualStudio](https://gitter.im/Microsoft/VisualStudio) Gitter room.

**Comment by tverweij** [comment]
@sharwell 
I agree, but my experience is that nobody is listening there ....

@ocdtrekkie 
Maybe a setting for VS: list of extensions that should be opened with an external program.
Defaults for me: docx, xlxs, pdf

**Comment by ocdtrekkie** [comment]
@tverweij I agree it would be good to be configurable, and that those are reasonable defaults, being common formats which don't open well in a code editor.

**Comment by tverweij** [comment]
Looks likes it finally works in VS2017: right click, open with, set default (was there for several versions, but did never survive a VS restart.
This issue is now closed because it is not vblang
