### ISSUE TITLE
Auto call Dispose for IDisposable objects and COM proxies

### ISSUE THREAD

**Issue by tverweij** [dotnet/vblang#263]
In VB6, the com objects where released as soon as the reference count reaches zero.
In VB.Net, we have to call Dispose by hand, use a Using construct or wait until the GC cleans it up.

I had one simple application, that crashed all the time - took me more than an hour to find out that the cause was that I did not dispose a Net.NetworkInformation.Ping object.
It would be a nice feature when Dispose is called automatically as soon as a disposable object gets out of scope - manual memory management should not be needed for VB.Net.

COM proxies should be generated as IDisposable objects - releasing the COM object when dispose is called.

**Comment by ericmutta** [comment]
> @tverweij It would be a nice feature when Dispose is called automatically as soon as a disposable object gets out of scope...

I think this is one of those things that are more complicated than they first appear. For starters, the scope and life-time for an object may be distinct. For example if you store an object in a local variable, then use it as a function return value, the variable goes out of scope but the object can't simply be disposed because a reference to it has been returned to the caller:

```vb
Public Function ReturnObject() As Object
  Dim obj = New Object 
  Return obj 
  'the variable obj goes out of scope here but the object it references must stay alive.
End Function
```

There can also be hidden references to an object that was originally referenced by a variable that goes out of scope:

```vb
Public Sub UseObject()
  Dim obj = New Object 
  SomeFunction(obj)
  'the variable obj goes out of scope here but the object it references may still be alive...
  '...if SomeFunction put it into a long-lived cache for example.
End Sub
```

The only safe way to automatically dispose an object in the above cases is to scan memory for references to the object (which is what so called "mark-and-sweep" garbage collectors do).

In essence the automation is already there. **But I certainly agree with you that there's room for improvement with this whole "manually calling Dispose" business.** Sooner or later you get it wrong and you get the [ObjectDisposedException](https://msdn.microsoft.com/en-us/library/system.objectdisposedexception(v=vs.110).aspx) to remind you that you are having a bad day 😄

**Comment by tverweij** [comment]
I think there must be some reference counter for the GC to work - so It could be called as soon as the reference count reaches zero.

**Comment by KathleenDollard** [comment]
.NET does not use reference counting for GC.

**Comment by tverweij** [comment]
Then I think this request can be closed with a "Not Possible" label.

**Comment by sharwell** [comment]
@tverweij we are working on code analyzers intended to identify these problems at compile time so they are less frequent in production, but this work is still in the early stages. @mavasani should be able to point you in the direction of our prototype work if you are interested in watching progress there.
