### ISSUE TITLE
Can The Visual Basic DLL Be Open Sourced?

### ISSUE THREAD

**Issue by RealDotNetDave** [dotnet/vblang#280]
The Microsoft.VisualBasic assembly has a lot of great code in it that makes it easy to do common tasks. There hasn't been any new features added in a long time. Is it possible to open-source it so the community can contribute and/or port to .NET Core?

David McCarter

**Comment by VBDotNetCoder** [comment]
I understood that VB is already open sourced

**Comment by Nukepayload2** [comment]
@VBDotNetCoder The Microsoft.VisualBasic.dll is not open sourced. If you search "MsgBox" on https://referencesource.microsoft.com , you will see declarations rather than implementations.

**Comment by ocdtrekkie** [comment]
I'd love to go in and see what some of the My namespace stuff does, in particular. Sometimes I started with My namespace stuff, needed to go further, and had to look for the regular .NET equivalent. And I've figured out that My sometimes definitely does things slightly differently than the .NET Framework counterparts.

**Comment by AnthonyDGreen** [comment]
I would love to see an open-source, .NET Standard targeted, out-of-band NuGet deployed, VB runtime library that's evolved with the language and platform (e.g. `Async` versions of File I/O APIs). It doesn't (shouldn't) be what's shipped in the .NET Framework for back-compat reasons.

**Comment by ocdtrekkie** [comment]
@AnthonyDGreen Is there any particular reason Microsoft would have not to share the existing .NET Framework version we all work with though? At the very least, if one was developing or working on a new modern version, it'd be useful to be able to refer back to the original to see what was done or how it worked.

**Comment by AnthonyDGreen** [comment]
That's a question for @KathleenDollard .

**Comment by ocdtrekkie** [comment]
This seems to be exciting news for those hoping for this! https://github.com/dotnet/corefx/issues/26386#issuecomment-400053156

**Comment by KathleenDollard** [comment]
There's good news and bad news I'm afraid. 

The good news, is that the Visual Basic runtime (visualbasic.dll) is moving into corefx. This means it's happening, and it plugs a very large hole in the Visual Basic experience on .NET Core. 

The Core version of visualbasic.dll has always been open source because corefx is, so this issue is on it's way to being closed. I'll leave it open for now and added some labels to clarify the status - we aren't doing any work here, and if the corefx folks have questions we'll add specific issues for that. 

The less good news is that this is part of the groundwork for .NET Core 3.0. We don't have plans to put this back into .NET Core 2.n. The reason is that we anticipate Visual Basic programmers to move quickly to .NET Core 3, because the .NET Core 2.n experience is so sub-opitimal. 

Watch the corefx issue for info on how you can help this effort if you are interested.

**Comment by craigajohnson** [comment]
@KathleenDollard nothing bad at all about the above, we would immediately move to 3.0.

**Comment by danmosemsft** [comment]
The .NET Framework code for this assembly is now public and we are tracking porting progress in https://github.com/dotnet/corefx/issues/31181. Contributions welcome there.

**Comment by KathleenDollard** [comment]
:-)

This will be a relatively easy way you can make a contribution to the future of VB.NET!

**Comment by DualBrain** [comment]
Isn't the OP request for this issue essentially resolved with the work that it taking place (and tracked separately over at dotnet/corefx#31181)?

**Comment by KathleenDollard** [comment]
At then suggestion of @DualBrain, I am closing this issue. 

A set of VisualBasic.dll has even ported to .NET Core 3.0, available starting in Preview 6. 

Please make comments on missing features individual issues.
