### ISSUE TITLE
Do away with Root Namespace and adopt C#'s Default Namespace

### ISSUE THREAD

**Issue by Echo-8-ERA** [dotnet/vblang#302]
One of the first things I used to do in VB projects is to clear the Root Namespace field in a project's property page. With .Net Core, this option doesn't work any more and I have to add a MSBuild target to clear the RootNamespace property since it automatically gets filled in with the assembly's name at the start of the build if it's empty.

I could start prefixing all my namespace declarations with `Global`, but that's kind of unintuitive.

**Comment by ericmutta** [comment]
> @Echo-8-ERA Same with having Option Explicit and friends - I put them in every code file rather than just setting it project wide.

This is one of those "personal preference" things. For example, I like that I DON'T have to import namespaces or specify options in every file (in the spirit of [OnceAndOnlyOnce](http://wiki.c2.com/?OnceAndOnlyOnce) as well as [DontRepeatYourself](http://wiki.c2.com/?DontRepeatYourself)). VB as always is very flexible in this regard, you can choose to do things at the project level or at the file level or a mix of both (I miss this flexibility when writing C#). It's also very cool that you never have to start with [118 lines of import statements](https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/core/java/android/view/View.java) because the language (Java in this case) forces you to be explicit.

There's a flip example, where I DO like to be explicit: prefixing instance member variables with `Me`. VB allows both options and some people don't like prefixing with `Me`. The flexibility is nice, though I do think it would be handy to get a compiler option for enforcing consistent usage across an entire project. So in your case you could disable project-level settings and the code would refuse to compile unless you were explicit in each file :+1:

**Comment by Echo-8-ERA** [comment]
To be honest, this issue only came about because .Net Core changed how an empty Root Namespace gets handled. Pre-.Net Core, leaving `<RootNamespace>` empty in the *.vbproj worked as intended. Now it gets set to the value of `<AssemblyName>` if `<RootNamespace>` is empty. Having to stick:
```xml
<Target Name="ClearRootNamespace" BeforeTargets="BeforeBuild">
  <PropertyGroup>
    <RootNamespace/>
  </PropertyGroup>
</Target>
```
Into my *.vbproj feels very hackish and un-VB-like.
---
FAKE EDIT:
Nevermind. I was basing this on my experiences with an old version of .Net Core that I had prior to using FreeBSD as an OS for a few months. Just noticed now that the latest version doesn't have this issue.

**Comment by AdamSpeight2008** [comment]
@Echo-8-ERA Have you also considered `Namespace Global`, i think it developed because of this problem.
