### ISSUE TITLE
Type Inference for Func and Action

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/vblang#345]
We should consider changing the inferred type of `Func(Of T)` from `Expression(Func(Of T))` to `Func(Of T).
Similiarly for `Action(Of T)` from `Expression(Of Action(Of T))` to `Action(Of T)`.

As it (in my opinion) the most likely type, 
```vbnet
Dim IsOdd As Func(Of Integer, Boolean) = Function(Value As Integer ) ((Value Mod 2) = 1)
Dim IsOdd = Function(Value As Integer) ((Value Mod 2) = 1)
```
To clear I'm saying that the second line should be valid.

**Comment by jrmoreno1** [comment]
@AdamSpeight2008: it is valid, the resulting type is --
     
       VB$AnonymousDelegate_0`2[System.Int32,System.Boolean

**Comment by JustNrik** [comment]
Bot are valid for me, I tested and both prints the same result with option strict on. Maybe you have option infer off?

**Comment by zspitz** [comment]
I could hear a reason to avoid inferring anything (as C# does). Consider the following EF code:
```vb
Dim ctx As MyDbContext
Dim filter = Function(x As Person) x.LastName.StartsWith("A")
Dim qry = ctx.Persons.Where(filter)
Dim lst = qry.ToList
```
Because `filter` has been inferred as a delegate and not an expression, the `Enumerable.Where` method will be used instead of `Queryable.Where`. This means all the `Person` records will be loaded into memory, before being filtered using the delegate; instead of the expression being used to filter the `Person` records on the server side.

This happens silently -- there is no compiler error or warning.
