### ISSUE TITLE
Autoconvert + to & for strings, remove + for Strings over time

### ISSUE THREAD

**Issue by paul1956** [dotnet/vblang#363]
Allowing + for string concatenation just causes hidden bugs when String + Integer gets missed by compiler with Option Strict Off. It would be better to phase out + for strings or have the IDE auto-convert it at a future major release during cleanup. It could be made a warning, then error. There are requests to allow this to be a style choice, I think that is a bad idea.

**Comment by rskar-git** [comment]
Note that 'String + Number' (and 'Number + String') which results in a number also happens in some flavors of SQL:

    SELECT 1 + "2"; -- MS SQL SERVER

    SELECT 1 + "2" FROM DUAL; -- Oracle, MySQL

    SELECT 1 + "2" FROM sysibm.sysdummy1; -- DB2

That's probably why Visual Basic classic went this way too, especially for doing expressions in Access database queries. (And VB.NET continues this way.)

The upside of `&` is one is assured of always getting a string, so it makes sense to favor it over `+`. However, I think a warning about `+` (which one can opt out of) should be enough. Besides, this string-and-a-number thing also plays through on comparison operators: That same warning should apply to them (e.g. `=`, `<=`, `<>`, etc.) as well.

**Comment by paul1956** [comment]
@rskar-git If you have Option Strict ON, VB correctly flags the error at compile time but with Strict Off you get a runtime error, why this is ever allowed is a mystery.

**Comment by rskar-git** [comment]
>why this is ever allowed is a mystery.

I think I already solved that mystery: "...also happens in some flavors of SQL...Visual Basic classic went this way too...for doing expressions in Access database queries."

What `Option Strict On` does is it disables much of the implicit conversions that VB would otherwise allow. On a technicality, something like 'Number + String' is really mapped to 'Number + Number' so that the String gets implicitly converted to a Number.

Furthermore, consider carefully what you are asking for. Something like this is legal VB syntax today:

    Function PlusTwo(v As Double) As Double
        Return v + 2
    End Function

    Console.WriteLine(PlusTwo("1"))

For better or worse, VB is a king of implicit conversions. `Option Strict On` is for people who are bugged by that (often for very good reasons). 

But try this: In the project properties window, on the Compile tab, check out the Warning Configuration named "Implicit conversion". You can make that either a warning or an error. That will flag all String to Number situations (and other implicit conversions). It won't bother you about any Number-to-Number situations, such as Integer to Double. That might be enough.

Adding another Warning Configuration such as "Implicit conversion to numeric" would practically solve this `+` issue plus a lot of others.

**Comment by paul1956** [comment]
@rskar-git I though I knew VB well but I have no idea what your example would return, would it be 3.0 to CDbl(Asc("1")) so 50.0 and what if I pass "1X" I assume I get a runtime error.

**Comment by rskar-git** [comment]
@paul1956 We both know that VB isn't C/C++ (or C# or Java or ECMAScript...), so that sort of blind type-casting between character types and integral types (such as what `CDbl(Asc("1"))` would suggest) never happens.
 
And yes, of course `PlusTwo("1X")` gets a runtime error. The point is `PlusTwo("1")` returns 3.0, per the language specification, an implementation reality for reasons of legacy and history.

If that bugs you, and you'd rather not do `Option Strict On` (maybe because you still want to do late binding), then set Warning Configuration "Implicit Conversion" to "Error". That would solve both `+` and `PlusTwo` scenarios.

**Comment by franzalex** [comment]
It's for such reasons that I have set up my environment to always make projects be ```Option Explicit``` and ```Option Strict On```. 
Doing that prevent nasty surprises from popping up when it's least expected.

**Comment by rskar-git** [comment]
I just gave this a thumbs-down. I think folks are misunderstanding what is going on here in regards to this 'Number + String' business.

Dropping `+` for strings won't help. And it should also be pointed out that a whole lot of other languages use `+` for string concatenations anyway, such as C#, Java, C++, Python... 
 
The real issue here is implicit conversions - specifically the implicit (quiet) usage of `Narrowing` conversions. It's what allows something like this to be legal in VB:

        Dim o1 As Object = 123
        Dim o2 As Object = 987
        Dim x = o1 + o2 ' x will be an integer, value of 1110

If you find this sort of thing troublesome, then either use `Option Strict On` (which makes VB very C#-ish), or, alternatively, set Warning Configuration "Implicit Conversion" to "Error". That's all one needs to do. One can do it today.

If `+` for Strings gets dropped, then only `+` for numerics remain (not to mention any other type with a `+` defined). And now the situation only gets WORSE! Whether `"123" + "987"` or `123 + "987"`, you won't get the error you think you should have. Instead, you'll always get the result of `1110` at runtime. Unless you make use of `Option Strict On` or "Implicit Conversion" to get the desired compile-time error - in which case, what exactly is the improvement here?

Perhaps 'Number + String' should have resulted in a string and not a numeric from the start, but that ship has already sailed. It's too late for that. Dropping `+` for strings won't help at all.

**Comment by paul1956** [comment]
With what I learned about Warning Configuration "Implicit Conversion" to "Error". I agree this should be closed.
