### ISSUE TITLE
Missing documentation of NameOf in VB.NET

### ISSUE THREAD

**Issue by zspitz** [dotnet/vblang#366]
Doesn't appear to exist at [the language reference](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/).

The link at the [What's New](https://docs.microsoft.com/en-us/dotnet/visual-basic/getting-started/whats-new#visual-basic-14) page points to the [C# documentation](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/nameof).

**Comment by KathleenDollard** [comment]
The VB.NET spec is a spec for a subset of the language that is required to call it VB.NET. There are a number if things that would be considered an important thing in the language that is not in the spec by design. 

The reason for this is partly historical. Platforms (like Windows Phone) needed to know what to install to have VB. For some of these platforms it was obvious that it wasn't all of it because there was no WinForms. In making the split, the decision was made to keep the spec requirements small to encourage adoption. 

If we were to change this, it would be a huge documentation and spec issue.

**Comment by zspitz** [comment]
@KathleenDollard There seems to be some confusion here -- I was referring to the documentation, not the spec documents -- although I am at fault for filing the issue here instead of at https://github.com/dotnet/docs. Since @Berrysoft has already opened an issue there, I'm closing this one.

**Comment by jrmoreno1** [comment]
@zspitz nice to have a link to the other issue 
https://github.com/dotnet/docs/issues/9690

**Comment by zspitz** [comment]
@jrmoreno1 On GitHub, when you reference issue A from issue B, issue B gets an automatic link to issue A:
![image](https://user-images.githubusercontent.com/312166/50549312-63f7f180-0c63-11e9-9736-caef96db0f1d.png)

**Comment by jrmoreno1** [comment]
@zspitz sorry, missed that. Knew about the cross linking, just missed the reference
