### ISSUE TITLE
Proposal: For While loop

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/vblang#392]
Proposal: For While loop
I suggest to add a more general for loop similar to C# for loop. I think this is the suitable VB syntax for it: 
```VB.NET
For I = 0 While I < 100 Let I *= 2
      Console.WriteLine(I) 
Next
```

This can be done today by while loop (which it should be lowered to):
```VB.NET
Dim I = 0 
While I < 100 
      Console.WriteLine(I) 
       I *= 2      
End While
```

For while is a more neat syntax, and has the benefit of declaring I in its scope.

The equivalent For loop should be:
```VB.NET
For I = 0 To 99 step I *= 2 - I
      Console.WriteLine(I) 
Next
```

Which will not compile, and of course less efficient and less readable!

The for while loop will bridge the gab between VB and C# in this area, and can be done without adding any new keywords.

Not that we can remove the while part, or the Let part like in C#:

```VB.NET
For I = 0 Let I *= 2
      Console.WriteLine(I) 
      If I > 99 Then Exit For
Next
```

```VB.NET
For I = 0 While I < 100
      Console.WriteLine(I) 
      I *= 2
Next
```

If the declaration part is removed, while keword is removed also:
```VB.NET
Dim I = 0
For I < 100 Let I *= 2
      Console.WriteLine(I)
Next
```

```VB.NET
Dim I = 0
For I < 100 
      Console.WriteLine(I)
      I *= 2
Next
```

**Comment by pricerc** [comment]
I had to think about this a bit. There is some appeal in the proposal, especially around declaring the 'indexer' as part of the loop syntax. But I don't think it justifies further murkiness in VB looping.

Two main points:
1) We already have a myriad of ways of looping (for..next, for each..next, do while|until..loop, do..loop until|while) ; do we really need yet another one?

2) The C# for loop received a dishonourable mention in Eric Lippert's [Top 10 Worst C# Features](http://www.informit.com/articles/article.aspx?p=2425867), so I'm not sure it's something we should be seeking to replicate. (thanks @zspitz for the link to that article supplied in #388)


your example:
```VB
Dim I = 0 
While I < 100 
      Console.WriteLine(I) 
       I *= 2      
End While
```

Is clear and has worked well for decades (Although I'd probably use the `Do..Loop` version).

Your proposal doesn't even save any keystrokes (assuming you're using Visual Studio, which adds the loop ending clause for you.

To paraphrase My comments from elsewhere in this forum:
>Changes to VB should prioritize language stability and ease-of-mainteance over 'cool new tricks' or 'shortcuts'. VB's future should be about improving the compiler while keeping it an easy-to-master, easy-to-read language, for the benefit of the developers using it. I would prefer new features to be about new functionality and/or fixing anomalous or inconsistent behaviour, not new ways to do old things. For me, I don't think this proposal would achieve these.

**Comment by VBAndCs** [comment]
@pricerc
I agree with most of your points. I love VB syntax and think it is the highest level syntax ever, but this shouldn't prevent VB benefit from other language advantages. C# for loop is more powerful, although its bad syntax, which I gave the VB taste in my proposal.
I also agree with many others that see that c# lambda expressions have a better syntax than VB's. At least we can use `Fnc(x) => x+1` instead of `Function(x) x+1`

The sad fact is that market roles are not always fair! VB.NET should have prevailed but recently, I see almost all new .net programmers learning C# not VB, as a result of MS decision to cage VB in Windows, and take C# to other OSs!
So, at least we can borrow some god features from C#. Not to mention VB should have all new features in C# 7 and C# 8.

**Comment by rskar-git** [comment]
>C# for loop is more powerful...

No, it is not, it is just a way to repackage a `while` loop. If what you want is something visually compact, your example can be done this way today:

    Dim I = 1 : While I < 100
        Console.WriteLine(I)
        I *= 2 : End While

(I think you meant `Dim I = 1` - `I` starting at zero goes nowhere!)

VB.NET also has iterators (just like C#)! So if a certain way of doing loops becomes a pattern, you can use them instead:

    Iterator Function PowersOfTwo(Limit As Integer) As IEnumerable(Of Integer)
        Dim i As Integer = 1
        Do While i < Limit
            Yield i
            i *= 2
        Loop
    End Function

    ' ...
    
        For Each J In PowersOfTwo(100)
            Console.WriteLine(J)
        Next

If you figure your need for a fancy loop is kind of one-off, you can use a lambda:

    For Each J In (Iterator Function()
                       Dim i As Integer = 1
                       Do While i < 100
                           Yield i
                           i *= 2
                       Loop
                   End Function)()
        Console.WriteLine(J)
    Next

It should be pointed that ye olde `For ... Next` loop is far more convenient than the C-style `for`:

    For i = 1 To 10 Step 2
        Console.WriteLine(i)
    Next
    
versus

    {int i_last=10, i_step=2; for(int i = 1; i <= i_last; i += i_step) {
        Console.WriteLine(i);
    }}

Not to mention that VB provides far more granular control over breaking out of loops than C#!

>I see almost all new .net programmers learning C# not VB, as a result of MS decision to cage VB in Windows, and take C# to other OSs!

Well, yes, C# is an obvious alternative to Java, and (as a long term aim) it is a plausible alternative to C++. In many ways, .NET is C#'s world, and VB just lives in it. But take heart, as a practical matter, VB is still widely used - and TIOBE shows it trending up! (Also, VB in all flavors is in the top 20 of PYPL).

But as far as other OS's are concerned, VB.NET can go wherever .NET goes. E.g. On Linux since the days of Mono. To a limited degree, on Android (via Xamarin). There are Apple Macintosh programmers doing VB.NET with Visual Studio Code. It far from "game over".

**Comment by VBAndCs** [comment]
@rskar-git
> (I think you meant Dim I = 1 - I starting at zero goes nowhere!)
Sorry.

What about this:
```VB.NET
For x = 1, Y = 1 While x < 12 and y < 100 Let x +1= 2, y *= 2
      Console.WriteLine(I) 
Next
```

It is the compact form of:
```VB.NET
Dim x = 1, Y = 1 
While x < 12 and y < 100 
      Console.WriteLine(I) 
      x +1= 2
      y *= 2
Next
```

And I don't conceder :  a god solution. I never used it since VB.NET. Back in days of VB5, I was fond of writing `Else: something` but didn't last long.

**Comment by VBAndCs** [comment]
Any way, the real reason that I thought of this, is that I am thinking of writing a VB# compiler that emits C# code. The Idea is to make VB# have a syntax very close to C#, and have the same symantcs and behaviors of C# compiler, so I can easily add all the new feactures added in C# 7 and 8, and make VB# work on ASP.NET and Xamarin by compiling it to C#. 
I don't know if this is doable (not the translation part, as I found a project to do so already), and I just started to study Roslyn. This is why I thougth of a For while loop.

**Comment by pricerc** [comment]
> 
> What about this:
> 
> ```vbnet
> For x = 1, Y = 1 While x < 12 and y < 100 Let x +1= 2, y *= 2
>       Console.WriteLine(I) 
> Next
> ```
> 
> It is the compact form of:
> 
> ```vbnet
> Dim x = 1, Y = 1 
> While x < 12 and y < 100 
>       Console.WriteLine(I) 
>       x +1= 2
>       y *= 2
> Next
> ```

Give me your second example any day. 

It's much easier to read and see what's going on. There is no benefit that I can see to your proposed syntax, which turns something obvious at a glance (your second example, even with its errors - what does x +1 = 2 mean?) into something that has to be mentally decoded. 


So actually, more like this:
```VB
Dim x = 1, y = 1
While x < 12 AndAlso y < 100
	Dim I = x * y
	Console.WriteLine(I)
	x = x + 2
	y = y * 2
End While
```


The point of a high-level programming language is to allow humans to tell a computer what to do, in a way that's easy for humans to write and, more importantly, in a way that is *easy to read*. 

I think that programming language 'efficiency' is best measured by the ability of a piece of code to convey its intent to someone who is seeing it for the first time, not by any other measure, and definitely not by how short the code is. In this regard, I think VB is a *very* efficient language.

In your examples, the current way of performing the loop is instantly obvious, and would be to the non-programmer consultants I often work with. On the other hand, I find your proposed syntax hard to read, mostly because *there's too much happening all on one line*. 

Your example even requires *MORE* typing. 

```VB
For x = 1, Y = 1 While x < 12 and y < 100 Let x += 2, y *= 2`
```
is 60 characters.

```VB
Dim x = 1, y = 1
While x < 12 And y < 100
	x += 2
	y *= 2
```
is 57 characters (including the tabs and line-feeds).


So I think it wise to not think of 'compact' as a goal in itself, as in my experience, 'compact' and 'legible' are more often than not incompatible, and what appears compact at first glance, or in theory is not always compact on closer inspect, or in practice.

**Comment by pricerc** [comment]
> The Idea is to make VB# have a syntax very close to C#, and have the same symantcs and behaviors of C# compiler

See, that's where we will likely always differ.  You're talking about C# with curly brackets replaced with words. To me, that's lacking in ambition, and I personally don't see the value. 

If that's your goal, then you're talking about something that isn't VB (I guess that's why you're calling it VB#); it would be C# for people who don't like '{' and '}'. I wish you well with your project; but, with respect, that doesn't really belong on *this* forum, which is for VB, not VB#.

**Comment by KathleenDollard** [comment]
@VBAndCs 

I once dreamed of a VB that was C# in a nicer form. I gave up on it years ago when I began to understand how many differences there are - it really would be sort of a compromise on everything language I think - and certain things would be very hard to express. 

If you do go that route, here is [An Exhausting List of Differences Between VB.NET and C# ](https://anthonydgreen.net/2019/02/12/exhausting-list-of-differences-between-vb-net-c/)

Selfishly, I hope if you are able to get deep enough in Roslyn to do this, you'll consider instead contributing to VB.NET in Roslyn or do more work on the very interesting XML Literals suggestion you made. Those things would help everyone.

**Comment by VBAndCs** [comment]
@KathleenDollard
> Selfishly, I hope if you are able to get deep enough in Roslyn

I did start reading about rosyln, even about creating compilers. But the VB Razor stopped all that for while!
Thanks.

**Comment by KathleenDollard** [comment]
I am very interested in the VB Razor work that you are doing

**Comment by VBAndCs** [comment]
@KathleenDollard 
Thanks. I will call it Vazor :)
The problem is that it needs more work to process the generated Html to resolve paths and process asp attributes and so. I need to follow the steps of the Razor View engine with making changes to deal with HTML string instead of cstml file. The problem is that I failed to build the MVC Project until now. I am using VS 2019 preview, and the preview versions of .NET Core cause many issues! I am walking in the dark here!
I thought of a trick to save the generated HTML from vazor in a chtml files and let the Razor complete the work, but this means saving a new file per page request! The solution I can think of for this is to convert vbxml to cshtml with a simple approach:
1- define a property for each `<%= %>` placeholder,  move the expression to this property, 
and replace the placeholder with @PropName. This will generate a valid chtml file!
2- pass all the properties with the model data.
3- Let Razor take action!
(All these points needs solutions)
I think the amount of work needed for this solution is less than modifying the razor. It is easier for me to build a new code to implement an idea, than analyzing a complex code and try to modify it without help.
It will be helpful to hear your advice here.

**Comment by KathleenDollard** [comment]
I love Vazor!

To break this down...you may need an entire "generated" project with the views to do .cshtml, because .cs and .vb aren't supported in the same file. I wonder if that would be a good thing because it could potentially be a backdoor if the generation wasn't complete. It is possible with that approach that you could always generate complete files (significantly easier than inserting into files) and it may be easier to insert a new project into the build than to insert prior to Razor in the build pipeline. The last is because (assuming it was OK to do more recompiles) the generation could be in the actual build, not in the Razor last minute interpretation step.

**Comment by VBAndCs** [comment]
I implementes this idea in [ZML](https://github.com/VBAndCs/ZML) as a suitable representation for C# loops in xml tags:
```xml
<z:for i="0" while="i < Model.Count" let="i++">
  <p>@i</p>
</z:for>
```

it generates:
```C#
@for (var i = 0; i < Model.Count; i++)
{
  <p>@i</p>
}
```

I allowed to drop the `let="i++"` attr and assume it is the default. I also allowed the VB for loop form. This will generate the same C# code in the last sample:
```xml
<z:for i="0" to="Model.Count - 1">
  <p>@i</p>
</z:for>
```
