### ISSUE TITLE
Question: is this behaviour of DirectCast by design?

### ISSUE THREAD

**Issue by ericmutta** [dotnet/vblang#416]
I have come across what I consider to be strange (if not buggy) behaviour of either the `DirectCast` operator, or the debugger, or both...but I can't say either way so I would like to get other's thoughts on this before posting somewhere more appropriate.

Type and run the following code in a VB console project:

```vb
Public Module Module1
  Public Enum ECountries
    Tanzania = 1
    England = 8
    America = 56
    China = 92
    Russia = 10
  End Enum

  Public Enum EColours
    Red = 50
    Blue = 12
    Green = 36
  End Enum

  Public Sub Main()
    Dim countriesA As ECountries() = DirectCast([Enum].GetValues(GetType(ECountries)), ECountries())
    Dim countriesB As ECountries() = DirectCast([Enum].GetValues(GetType(EColours)), ECountries())

    For Each countryA In countriesA
      Console.WriteLine($"{countryA.ToString()} = {CInt(countryA)}")
    Next

    For Each countryB In countriesB
      Console.WriteLine($"{countryB.ToString()} = {CInt(countryB)}")
    Next

    Stop
  End Sub
End Module
```

What we have is two enum types `ECountries` and `EColours`. They have completely different purposes and I have assigned each enum member a unique integer value that is not found in the other enum type, so their values have nothing in common.

The following two lines are of interest:

```vb
    Dim countriesA As ECountries() = DirectCast([Enum].GetValues(GetType(ECountries)), ECountries())
    Dim countriesB As ECountries() = DirectCast([Enum].GetValues(GetType(EColours)), ECountries())
```

The first line declaring `countriesA` and initialising it with an array of values from `ECountries` retrieved at run-time works just as expected. When the program stops and you hover over 
`countriesA` , the debugger shows the countries as defined:

![direct_cast_1](https://user-images.githubusercontent.com/20465797/56322376-96c1e900-6171-11e9-8c29-96901a54e410.png)

The second line contains an error:

```vb
    Dim countriesB As ECountries() = DirectCast([Enum].GetValues(GetType(EColours)), ECountries())
```

Here we are retrieving an array of the enum members of `EColours` but are then `DirectCast`-ing to an array of enum members of `ECountries`! **I was expecting an exception to be thrown at run-time saying something like `you can't convert array of EColours to array of ECountries` but no such exception is thrown.** It just chugs along and if you hover over `countriesB` the debugger shows this:

![direct_cast_2](https://user-images.githubusercontent.com/20465797/56322767-9bd36800-6172-11e9-84a5-a55031889c7a.png)

`countriesB` is explicitly defined as an array of `ECountries` but the debugger is showing an array of the enum members from `EColours`. **How on earth is it making that connection after DirectCast has converted the result of `Enum.GetValues` to an array of `ECountries`?**

To put it simply, why does this not fail:

```vb
    Dim colours As EColours() = {EColours.Blue, EColours.Red}
    Dim countries As ECountries() = DirectCast(colours, ECountries())
```

...we are DirectCasting an array of EColours to an array of ECountries and no exception is thrown. Why? The [docs say](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/operators/directcast-operator):

> DirectCast requires an inheritance or implementation relationship between the data types of the two arguments. This means that one type must inherit from or implement the other.

Does such an `inheritance or implementation relationship` exist between arrays of two distinct enum types? I don't see how it could, which is why I was expecting DirectCast to fail at run-time but strangely enough, it does not fail at all!

**Comment by pricerc** [comment]
Interesting results.

LinqPad returns:
`
Tanzania = 1
England = 8
Russia = 10
America = 56
China = 92
12 = 12
36 = 36
50 = 50
`

In the absence of other decoration, they're just all integers. So (and I'm guessing here), I'd say that it's the debugger has kept track of the underlying type for the array of colours, for display purposes, but otherwise, the Cast just sees two integers.

I think this is part of the reason for the development of [the enums.Net project](https://github.com/TylerBrinkley/Enums.NET)

**Comment by franzalex** [comment]
This is by design, as a result of the way Enums are represented in VB.NET.  
In VB.NET, Enums are essentially a thin shell around numeric constants. This is corroborated by @AnthonyDGreen in his article [An Exhausting List of Differences Between VB.NET & C#](https://anthonydgreen.net/2019/02/12/exhausting-list-of-differences-between-vb-net-c/#35).

So, what the direct cast is doing is to simply map the 'names' from the `ECountries` enum to the values of `EColors`. Where there are no `ECountries` to map to the values obtained from `EColors`, the underlying values are returned 'undecorated'.

I observed this behaviour all the way back in 2005, when I switched from VB6 to VB.NET and I remember writing code like the following to inter-convert enum values (a practice I now strongly advise against).

    Public Enum Fruits
        Apple = 1
        WaterMelon = 2
        Pawpaw = 4
        ' more values
    End Enum

    Public Enum FruitSalads
        AppleMelon = 3
        ApplePawpaw = 4
        ' more values
    End Enum

     ' conversion from fruits to fruit salad (highly discouraged)
    Dim salad = DirectCast(Fruits.Apple + Fruits.Melon, FruitSalads)

Such code works because VB.NET simply adds the values of the `Apple` and `Melon` and then finds a `FruitSalad` whose value matches the result obtained previously. This, in my opinion, is one of the beautiful things VB.NET allows developers to do. However, left unchecked, this can lead to a lot of bad code.

**Comment by ericmutta** [comment]
> @pricerc: ....they're just all integers...
>@franzalex: In VB.NET, Enums are essentially a thin shell around numeric constants. 

You are both absolutely right and the link to the exhausting list given by @franzalex was really handy (that list _is_ exhausting but I now see it is worthwhile to read it all).

To drive the point home of enums being a thin wrapper over integers, you can make DirectCast fail by changing the underlying integer types of the enums:

```vb
  Public Enum ECountries As Integer '<-- use Integer type here.
    Tanzania = 1
    England = 8
    America = 56
    China = 92
    Russia = 10
  End Enum

  Public Enum EColours As Long '<-- use Long type here.
    Red = 50
    Blue = 12
    Green = 36
  End Enum
```

Now the following code fails with an error on the DirectCast call:

```vb
    Dim colours As EColours() = {EColours.Blue, EColours.Red}
    Dim countries As ECountries() = DirectCast(colours, ECountries())
```

...the error message is even inline with the docs and says:

```
Value of type 'Module1.EColours()' cannot be converted to 'Module1.ECountries()' because 'Module1.EColours' is not derived from 'Module1.ECountries'
```

Because enums are just thin wrappers over integers the call `DirectCast(colours, ECountries())` is like trying to cast an array of longs to an array of integers, which should fail and does indeed fail with the above error message.

Learn something new every day!
