### ISSUE TITLE
Question -- Implicit conversion from numbers to string for VB.Net (without option strict off)

### ISSUE THREAD

**Issue by jrmoreno1** [dotnet/vblang#434]
Would implicit conversion from a number to a string be possible, or is it  ruled out due to signature collisions?  I.e. sub a(value as integer) vs sub a(value as string).

**Comment by AnthonyDGreen** [comment]
Wow. I didn't see this for almost 6 years. I haven't worked at Microsoft for 4 of them. My apologies.

If `Option Strict` is on, an implicit conversion from a numeric type to string would report an error. Not sure what you meant by "ruled out by signature collisions". If both overloads are present and you pass an integer, the integer overload should be chosen.

Again, apologies for not seeing this 6 years ago.

**Comment by jrmoreno1** [comment]
@AnthonyDGreen : no problem with not seeing it, especially for the last 4 years. :)

My question was meant to feel out the possibility of a change in how it was dealt with, and what I meant by signature collisions was it unduly complicating signature resolution if the conversion was implicit. Given current policies, it’s all moot.  

Integer to string errors were one of the most common errors I saw when turning on Option Strict on old projects, and the one that the makes the least sense to me. But thinking about it with what I know in 2022 and not what I knew 2016, the best answer is probably an analyzer/codefix.

**Comment by AnthonyDGreen** [comment]
Honestly, that's one reason why I dislike Option Strict On. It's a big coarse hammer that reports a lot of errors that probably shouldn't be. I plan to replace it with a suite of analyzers or fine compiler diagnostics in [my modded VB compiler](https://anthonydgreen.net/2022/08/20/introducing-modvb/)

One that annoys me is this

```
Dim b As Byte
b += 1
```

Or similar, I'm not at a computer right now to check but I know there's a scenario where the compound assignment errors with option strict because technically 1 is an Integer, not a byte.

These really should be stylistic configurations not hard and fast rules about narrowing vs widening conversions, though I also understand why Integer to String conversions are considered one and not the other.

What's the most valuable thing about Option Strict On to you?

**Comment by jrmoreno1** [comment]
@AnthonyDGreen : huh, I reported that (byte or unsigned byte addition) as bug for the csharp compiler many years ago.  

As for Option Strict On, part of it is or was tooling (it's possible that it was fixed), as finding late bound methods failed.  The other part of it is that I don't want or need late binding for methods, I'm not doing COM interop these days, and even when I was it was isolated to specific methods.  The type safety is great for programs with lots of similarly named enums.

And of course the whole "this" + 1 throwing an exception -- that would less of a problem if plus was disallowed for strings or if it resulted in an implicit conversion of the number to a string instead of trying to convert the string to a number.

**Comment by AnthonyDGreen** [comment]
Yeah, I plan to redo a lot of the warnings/errors in VB so that common-sense stuff behaves are you'd want, e.g:

* If a conversion of a literal would succeed at compile time, it should be legal.
* If a conversion of a literal would fail at compile time (`"Frank" -> Integer), it should be illegal, even if Option Strict is Off.

Individual controls for various types of conversions like `Boolean <-> String` conversions. I see on the web sometimes new programmers get cause by this:

```
If someString.Contains("A" Or "B") Then...
```

And folks on forums scream at them "TURN ON OPTION STRICT". But option strict just says a bunch of stuff is illegal without actually educating them on why that doesn't work or the correct way to write it. Even if I concede that implicit conversions between boolean and string are mostly useless (and they are), I still like implicit conversions for other combinations of types.
