### ISSUE TITLE
[Proposal] improvements on the [] bracket

### ISSUE THREAD

**Issue by xieguigang** [dotnet/vblang#56]
Currently the visualbasic ``[]`` bracket just enable user to escaping the vb.net keywords as legal identifier, and I think this ``[]`` bracket can be add more function

### 1 improvements on the tuple

The new tuple feature allows the function returns multiple values at once, currently if we want using the values in the tuple object as a **variable**, require the definition statement

```vbnet
' Function getValue() As (a#, b#)

Dim tuple As (a#, b#) = getValue()
Dim a# = tuple.a
Dim b# = tuple.b
```

And this is not the real tuple feature, for example, the tuple in python and matlab language,

```python
x, y = 1, 2;
print "Value of x , y : ", x, y
```

And i think the new tuple feature can be make some improvements using ``[]`` bracket, like:

```vbnet
Dim [a#, b#] = getValue()

Console.WriteLine($"a={a}, b={b}")

For Each [a#, b#] In getValues()
    Dim c# = a# + b#
Next
```

### 2. Numeric range

Currently, generates a numeric sequence can achieve by using function, like:

```vbnet
Dim indices%() = Range(1, 10)

For Each i% In Range(1, 10)
Next

' Or using tuple extensions
For Each i% In (1, 10).Range
Next
```

Probably, this can be more simplify by using ``[]`` bracket, like:

```vbnet
Dim Indices%() = [1: 10]

For Each i% In [1: 10]
Next
```

**Comment by AdamSpeight2008** [comment]
### Range Literal
If we have the range literal we should be able to express the clusivity *(inclusive or exclusive)* of the bounds. 
```vbnet
Dim r0 = [  0 : 10  ] ' 0 <= x <= 10  Inclusive Inclusive ==> 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
Dim r1 = [  0 : 10 )] ' 0 <= x <  10  Inclusive Exclusive ==> 0, 1, 2, 3, 4, 5, 6, 7, 8, 9
Dim r2 = [( 0 : 10  ] ' 0 <  x <= 10  Exclusive Inclusive ==>    1, 2, 3, 4, 5, 6, 7, 8, 9, 10
Dim r3 = [( 0 : 10 )] ' 0 <  x <  10  Exclusice Exclusive ==>    1, 2, 3, 4, 5, 6, 7, 8, 9
' r0 is the Default option
```

We could though enable the usage ` To (Step )` from for loops into more generalized meaning of range. (Note the clusivity bounds would be restricted to inclusive inclusive).
```vbnet
Dim r0 = 0 To 10 
```

**Comment by AdamSpeight2008** [comment]
Rewriting your example using the `extended To syntax`
```vbnet
Dim indice As New List(Of Integer) From 1 To 10 Step 2
```
```vbnet
For Each (sqr,cubic) In From i In 1 To 10 Step 2
		        Select (sqr:= i^2, cubic:= i^3)
  If cubic \ sqr = 3 Then
    ' blahblabla
  End If
Next
```
Already look in keep with the visual style of VBnet

**Comment by AnthonyDGreen** [comment]
Looks like there are multiple proposals here. One for tuple extraction, one for range expressions. We wouldn't use square brackets for tuple extraction. We're more likely to use a syntax that uses parentheses like tuple literals, e.g.:

``` VB.NET
Dim (x, y) = GetPoint()
```

A proposal for tuple extraction should be filed separately, with appropriate motivating examples from real code.

As for a range syntax we're more likely to consider a syntax inspired by the `For` loop and `Select Case` ranges, e.g.

``` VB.NET
Dim range = 5 To 100 Step 5
```

The other problem we (the LDM) had with `[1:10]` mapping to `Range(1, 10)` is that the second parameter of `Range` specifies a count rather than an upper-bound. That's clearer with the `X To Y` syntax proposed in #25.
