### ISSUE TITLE
[Proposal] RaiseEvent Object.Event

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/vblang#562]
Can VB allow calling a public event from outside its class? 
`RaiseEvent comboBox.SelectedIndexChanged(Me, e)`
And why it is prevented in first place?

**Comment by zspitz** [comment]
If you want something you can invoke from outside the class, use a delegate-returning field or property.

`Public` only means an outside subscriber can add or remove a handler.

**Comment by VBAndCs** [comment]
Not true. WPF already fixed this by providing a RaiseEvent method to fire whatever events the control has form outside. So, It is obviously something that developers want. I find it smarter to have this directly from the language, instead adding methods to each class to raise its events.

**Comment by zspitz** [comment]
WPF didn't "fix" the generalized .NET event mechanism -- I still can't use RaiseEvent on the [Elapsed](https://docs.microsoft.com/en-us/dotnet/api/system.timers.timer.elapsed) event of a [System.Timers.Timer](https://docs.microsoft.com/en-us/dotnet/api/system.timers.timer). Even within WPF, there are many events which are not `RoutedEvents`, such as `DataContextChanged`.

WPF routed events have a specific purpose: they enable user-initiated interactions -- such as keyboard presses or mouse clicks -- on a given object to be handled at a higher or lower level of the visual tree. Being able to raise events from outside the handling object is a requirement for this scenario.

**Comment by VBAndCs** [comment]
It is a common requirement, so that WinForma added PreformClick to buttons and menus. It is cheaper to solve this at the lang level, than writing endless codes in classes. The developer is the one who decides what is best for his goals, so, he can force raise the events or not.

**Comment by pricerc** [comment]
Making it easy for a programmer to do bad things doesn't improve a language.

Heck, why not just make SendKeys a first-class VB citizen? That would make for awesomely easy-to-maintain code. Not!

As pointed out. Events are there for an object to notify its consumers that something has happened, not the other way around. That's what properties and methods are for.

**Comment by zspitz** [comment]
> It is a common requirement, so that WinForms added PerformClick to buttons and menus.

I've never used WinForms, but in my brief review of various controls, I only found a method such as you describe -- a method specifically designed to raise an event -- for the Click event, and that only for buttons and menus; hardly an indication of a "common requirement".

Also, a case could be made for such methods to be available for simulating user interactions -- such as mouse clicks and keyboard inputs -- without actually having to press the mouse or keyboard. But adding members to the class which are only to be used while testing seems like a code smell to me; better to invoke the events via reflection.

> The developer is the one who decides what is best for his goals.

When you talk about the developer here, which developer do you mean?

* the designer / author of the class?
* or the consumer of the class?

The author of the class doesn't have to use an event; they can certainly choose to expose a `Public` delegate-type property or field, and thus allow consumers of the class to call the method(s) attached to the field or property.

Arguing that because there may be some specific cases where the consumer needs to raise the event, and that therefore all events should be raisable from outside the class; is akin to arguing that since some fields in some specific cases need to be `Public` and read/write, therefore all fields should be `Public` and read/write.

**Comment by gilfusion** [comment]
Overlooking the "why" for a moment in favor of "how"...

By default, auto-implemented properties come with a public (or whatever visibility you set the property as) getter, a public (same as before) setter (unless it's ReadOnly), and a private backing field. You can override this by implementing the property yourself and specifying the modifiers for the getter, setter, and backing field.

VB does have support for custom events ([see here for example](https://www.codeproject.com/Articles/229122/Add-Custom-Event-To-A-Class-in-VB-Net)), and maybe it would be worthwhile to add the ability to control the visibility of its parts (AddHandler, RemoveHandler, and RaiseEvent) like you can with the parts of properties.

**Comment by zspitz** [comment]
@gilfusion Or you could use some combination of a delegate-type property or field, which you could add to, remove from, or invoke as needed. And if there already exists a mechanism for these scenarios, why implement a new one in the language? Which brings us squarely back to the "Why" again.

The same argument could be made against property getter and setter syntax -- everything you could do with specialized property syntax, you could do with a set of methods. (AFAICT Java has been making this argument since the beginning.)  Except that in the case of properties, they enable a certain duality -- even though from inside the class they look like methods, from the outside they have the semantics of fields. Given that this is a very common scenario, it makes sense to introduce specialized syntax.

But the proposed usage of events conflicts with the fundamental design philosophy of events.

**Comment by CyrusNajmabadi** [comment]
This would break encapsulation of events, which would be a strong violation of the principles e originally designed them on.  I can' envision a world where VB would allow this.  If types want to allow external parties to invoke their events, they can do so already by exposing an appropriate method.  In the future, this could be done using source generators as well if you really wanted.

Closing this out.
