### ISSUE TITLE
possible VB.NET compiler bug using Null-conditional operator

### ISSUE THREAD

**Issue by gafter** [dotnet/vblang#69]
@stax76 commented on [Tue Jun 14 2016](https://github.com/dotnet/roslyn/issues/12027)

aaa() getting called looks like a bug.

```
Module Module1
    Sub Main()
        Dim s As String
        If s?.Contains("") AndAlso aaa() Then Console.WriteLine("bbb")
        Console.ReadKey()
    End Sub

    Function aaa() As Boolean
        Console.WriteLine("aaa")
        Return True
    End Function
End Module
```

---

@HaloFour commented on [Wed Jun 15 2016](https://github.com/dotnet/roslyn/issues/12027#issuecomment-226160008)

The reason is because the null-conditional operator isn't returning `False`, it's returning `Nothing`.  VB.NET does not treat `Nothing` as `False` when it comes to short-circuiting Boolean operations.

---

@HaloFour commented on [Wed Jun 15 2016](https://github.com/dotnet/roslyn/issues/12027#issuecomment-226162011)

The following MSDN page contains a table of how `Nullable(Of Boolean)` operands are compared.  When comparing a `Nullable(Of Boolean)` to a `Boolean` the VB.NET compiler implicitly converts the `Boolean` to a `Nullable(Of Boolean)`:

Under Comparing Nullable Types:
[Nullable Value Types](https://msdn.microsoft.com/en-us/library/ms235245.aspx)

Also, from the note:

> `AndAlso` and `OrElse`, which use short-circuit evaluation, must evaluate their second operands when the first evaluates to `Nothing`.

---

@stax76 commented on [Wed Jun 15 2016](https://github.com/dotnet/roslyn/issues/12027#issuecomment-226195592)

> VB.NET does not treat Nothing as False when it comes to short-circuiting Boolean operations.

Why does it work like this? It appears absolutely wrong to me.

---

@AdamSpeight2008 commented on [Wed Jun 15 2016](https://github.com/dotnet/roslyn/issues/12027#issuecomment-226286531)

@stax76 Null doesn't equal default(of T).
Think `Nullable(of Boolean)` of having 3 state.  `Do Not Know` , `False` , `True`
Also If I remember correctly VB.net has a stricter definition for `Nullable<T>` than C#. 

---

@HaloFour commented on [Wed Jun 15 2016](https://github.com/dotnet/roslyn/issues/12027#issuecomment-226306232)

C# doesn't permit implicit conversion from `bool?` to `bool`.  The expression `(s?.Contains("") && aaa())` would fail to compile.  You'd need to use the null-coalescing operator `??` to provide a default value, e.g. `(s?.Contains("") ?? false && aaa())`.

The VB.NET behavior does make sense if you view it in the context of a tri-state or a SQL-like `NULL`.  The lack of a value is not the same as a negative or false value, so it tests the next expression.  I can definitely see how it could be confusing, but it's been the behavior for evaluating nullable-Boolean expressions for over a decade and it would not be possible to change it even if it could be argued that it should be.

**Comment by Bill-McC** [comment]
Unfortunately not ;)
Consider this code:
`Dim maybe As Boolean? = Nothing
Dim uncertainty = maybe AndAlso False
Console.WriteLine(uncertainty = False)`

Because nothing and False is False, not nothing.  So in this case the And needs to be evaluated to see if the uncertainty expression returns Nothing or False (it can not return True)

I do think this is one of those language features that was too purist, but it is what it is. Worthy of a warning in the case of nullable AndAlso expensiveExpression, and a suggestion how to achieve the desired outcome by adding GetValueOrDefault, eg:
Dim uncertainty  = maybe.GetValueOrDefault AndAlso somecall()

Wish there was a better way :(

**Comment by AnthonyDGreen** [comment]
It has nothing to do with `Nothing`. It's really about [SQL ANSI_NULLS](https://docs.microsoft.com/en-us/sql/t-sql/statements/set-ansi-nulls-transact-sql)

Nullable value types in VB work like ISO-compliant null values in SQL which gives a consistent experience for the = operator whether in a LINQ query executed against a SQL provider or against CLR objects. C# went a different way. As explained [here](https://blogs.msdn.microsoft.com/csharpfaq/2004/05/25/why-dont-nullable-relational-operators-return-bool-instead-of-bool/) the primary motivation was consistency with existing C# conventions for checking null:

> A: In our initial designs, we spent a fair amount of time discussing what the behavior should be here, and how we should cross over from the three-valued nullable world to the two-valued “normal C#“ world. 
>
> Consider the following method:
> void Process(int? p)
> {
>     if (p == null)
>     {
>         // do some processing…
>     }
> }
>
> This seems like a very natural thing for a C# user to want to write. But if equality is three-valued, comparing anything to null always returns a null value (ie null isn’t equal to anything), and therefore such a comparison can never succeed. Instead, the user would have to write:
>
> if (!p.HasValue)
>
> or something similar. We decided that the value of having a model that was consistent with the way users were used to dealing with reference null was pretty high, and therefore decided to make the relational operators return bool.

Paul Vick explains [here](https://blogs.msdn.microsoft.com/csharpfaq/2004/05/25/why-dont-nullable-relational-operators-return-bool-instead-of-bool/), that because VB has always had separate =/<> and Is/IsNot operators this compromise wasn't necessary.

I concede this does cause confusion from time to time and we have considered warnings for the top offenders but I do believe this is by design.

**Comment by jrmoreno1** [comment]
@AnthonyDGreen : I agree that is what the specs say...

> In the lifted form of the AndAlso and OrElse operators, if the first operand was a null Boolean?, then the second operand is evaluated but the result is always a null Boolean?.

But that doesn't match what SQL does.  SQL doesn't do any short circuiting, but if you have a where clause or case condition of NULL = value or 1=1, it will match, while NULL = value and 1=1 will not.  The OR succeeds because it is not dependent upon the first value (null, true or false are all equivalent), the AND fails because NULL is NULL (not true, and not false).  As far as I know I haven't been bitten by this, but I would certainly have expected NULL OrElse True to evaluate to True.

Update:
And I would be correct:

	If Ctype(Nothing, Boolean?) OrElse True Then
		Console.WriteLine("The spec says this should happen, the reverse with AndAlso true does.")
		Console.WriteLine("Which is fine, but the right hand side IS evaluated so it doesn't prevent null value exceptions")
	End If
